site_name: Textual Shell

theme:
  name: "material"
  features: 
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - mkdocstrings

markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Widgets:
    - widgets/index.md
    - CommandList: widgets/command_list.md
    - CommandLog: widgets/command_log.md
    - Prompt: widgets/prompt.md
    - Shell: widgets/shell.md
    - Suggestions: widgets/suggestions.md

  - Commands:
    - commands/index.md
    - HELP: commands/help.md
    - SET: commands/set.md
    - COMMAND: commands/command.md

  - Implement Your Own: custom_commands.md
